spring.application.name=demo

spring.datasource.url = jdbc:postgresql://localhost:5432/user_management
spring.datasource.username = postgres
spring.datasource.password = 4mbgti5i@post
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema = inova_schema
